# Whether to use the broker to get the best relay based on location or use a hard-coded relay.
# default: true
useBroker = true
# default: https://broker.e4mc.link/getBestRelay
brokerUrl = "https://broker.e4mc.link/getBestRelay"
# default: test.e4mc.link
relayHost = "test.e4mc.link"
# default: 25575
relayPort = 25575
# Disables TLS certificate validation for relay connections.
# Use this only as a last resort if you're experiencing SSL certificate errors.
# This is insecure and not recommended.
# Instead, it is strongly recommended to install the Azul Zulu 8 JDK, which avoids these issues.
# For a proper fix, including how to import the certificate manually, see:
# https://github.com/xhyrom/e4mc-retro/issues/2#issuecomment-3102506009
# default: false
useInsecureTLS = false
# Allows use of certain dedicated server commands such as /ban and /whitelist
# default: true
restoreDedicatedCommands = true
# Whether to use whitelists on LAN worlds
# default: false
useWhiteList = false

